export interface WritingStyle {
  id: number;
  name: string;
  summary: string;
  planning: string;
  drafting: string;
  revising: string;
  voice: string;
}

export const WRITING_STYLES: readonly WritingStyle[] = [
  {
    id: 1,
    name: "the architect",
    summary: "build a visible hierarchy before filling it in",
    planning: "Map a thesis, section order, and the job of every paragraph before drafting.",
    drafting: "Construct the middle first, then add an opening and conclusion that lock onto that structure.",
    revising: "Move whole sections, remove structural repetition, and tighten every transition.",
    voice: "Ordered, composed, and explicit about how each idea connects.",
  },
  {
    id: 2,
    name: "the explorer",
    summary: "follow questions until a useful route appears",
    planning: "Generate competing questions, mark uncertain paths, and choose the most revealing route late.",
    drafting: "Start with discovery fragments and let the central claim emerge from what they uncover.",
    revising: "Cut dead ends, preserve one useful surprise, and reshape the route into a clear journey.",
    voice: "Curious, open, and progressively more certain.",
  },
  {
    id: 3,
    name: "the skeptic",
    summary: "stress-test every claim before accepting it",
    planning: "List the main claim, hidden assumptions, strongest objection, and evidence that would change the conclusion.",
    drafting: "Build from qualified claims and test each one against a concrete counterexample.",
    revising: "Remove overstatement, strengthen weak warrants, and make uncertainty precise.",
    voice: "Measured, exacting, and resistant to easy conclusions.",
  },
  {
    id: 4,
    name: "the storyteller",
    summary: "organize ideas through scene, tension, and payoff",
    planning: "Find a concrete opening moment, the tension it exposes, and the final insight that resolves it.",
    drafting: "Write vivid moments first, then bridge them with only the context the reader needs.",
    revising: "Sharpen the opening image, compress exposition, and make the ending echo the beginning.",
    voice: "Human, concrete, and paced like a narrative.",
  },
  {
    id: 5,
    name: "the minimalist",
    summary: "say the most with the fewest necessary parts",
    planning: "Reduce the request to one sentence, three indispensable points, and a list of details to omit.",
    drafting: "Write the shortest complete version in compact blocks with no decorative detours.",
    revising: "Delete duplication, shorten verbs and transitions, and make every sentence earn its place.",
    voice: "Spare, direct, and quietly confident.",
  },
  {
    id: 6,
    name: "the teacher",
    summary: "build understanding one rung at a time",
    planning: "Identify assumed knowledge, the core misconception, a simple example, and the order of conceptual steps.",
    drafting: "Explain from familiar ground toward the difficult idea, checking understanding through examples.",
    revising: "Replace jargon, repair skipped steps, and add one clarifying contrast where confusion is likely.",
    voice: "Patient, lucid, and encouraging without being simplistic.",
  },
  {
    id: 7,
    name: "the analyst",
    summary: "separate the problem into variables and relationships",
    planning: "Define the question, factors, constraints, causal links, and the standard for a good conclusion.",
    drafting: "Develop one factor at a time, then synthesize how the factors interact.",
    revising: "Correct category errors, balance evidence, and make causal language appropriately narrow.",
    voice: "Systematic, neutral, and evidence-conscious.",
  },
  {
    id: 8,
    name: "the dialectician",
    summary: "advance through claim, opposition, and synthesis",
    planning: "Write a thesis, its strongest antithesis, the real tension between them, and a possible synthesis.",
    drafting: "Give both positions genuine force before developing a third view that resolves or reframes the conflict.",
    revising: "Remove straw arguments, equalize the two sides, and make the synthesis more than a compromise.",
    voice: "Balanced, intellectually energetic, and comfortable with tension.",
  },
  {
    id: 9,
    name: "the mosaic",
    summary: "assemble meaning from small, contrasting fragments",
    planning: "Collect images, facts, short observations, and contrasts without forcing an early thesis.",
    drafting: "Write modular fragments in a deliberate sequence so their juxtaposition carries part of the argument.",
    revising: "Reorder fragments for resonance, remove explanatory glue, and add only the links readers truly need.",
    voice: "Textured, concise, and associative while remaining coherent.",
  },
  {
    id: 10,
    name: "the reverse engineer",
    summary: "start from the desired conclusion and uncover its prerequisites",
    planning: "State the target outcome, then work backward through the conditions, decisions, and facts required to reach it.",
    drafting: "Build the dependency chain from the deepest prerequisite toward the visible result.",
    revising: "Find missing dependencies, remove circular reasoning, and make each step verifiable.",
    voice: "Practical, causal, and relentlessly outcome-oriented.",
  },
  {
    id: 11,
    name: "the reporter",
    summary: "lead with what matters and support it with concrete detail",
    planning: "Identify the lead, the five essential questions, the strongest fact, and what remains unverified.",
    drafting: "Open with the newsworthy point, then descend through evidence, context, and consequences.",
    revising: "Move buried facts upward, remove speculation, and attribute uncertain claims clearly.",
    voice: "Crisp, factual, and readable under time pressure.",
  },
  {
    id: 12,
    name: "the scientist",
    summary: "move from hypothesis through evidence to bounded conclusion",
    planning: "Form a testable hypothesis, identify observations, alternatives, limitations, and what the evidence can support.",
    drafting: "Present the question, method of reasoning, evidence, interpretation, and limitations in sequence.",
    revising: "Separate observation from inference, test alternatives, and narrow claims to the available evidence.",
    voice: "Precise, transparent, and appropriately cautious.",
  },
  {
    id: 13,
    name: "the advocate",
    summary: "build a persuasive case around stakes and action",
    planning: "Define the audience, desired action, shared value, main resistance, and strongest supporting reasons.",
    drafting: "Connect the stakes to the audience, establish the case, answer resistance, and end with a concrete action.",
    revising: "Strengthen relevance, replace pressure with evidence, and make the call to action specific.",
    voice: "Convincing, purposeful, and respectful of the reader.",
  },
  {
    id: 14,
    name: "the reflector",
    summary: "develop insight by examining a change in understanding",
    planning: "Mark the initial belief, the experience or evidence that disturbed it, and the more nuanced view that followed.",
    drafting: "Move between observation and interpretation, showing how the writer's understanding changes.",
    revising: "Remove generic introspection, ground insights in specifics, and make the change in perspective credible.",
    voice: "Thoughtful, personal where appropriate, and self-aware.",
  },
  {
    id: 15,
    name: "the comparator",
    summary: "reveal the answer through disciplined contrast",
    planning: "Choose meaningful comparison criteria, establish a fair baseline, and predict where the contrast matters most.",
    drafting: "Compare point by point or case by case, keeping the criteria consistent.",
    revising: "Correct asymmetry, remove trivial contrasts, and turn comparison into a useful judgment.",
    voice: "Clear, even-handed, and decisive when the evidence permits.",
  },
  {
    id: 16,
    name: "the troubleshooter",
    summary: "move from symptom to cause to workable remedy",
    planning: "Separate symptoms from root causes, list constraints, rank interventions, and define how success will be checked.",
    drafting: "Describe the problem briefly, diagnose it, then present remedies in practical order.",
    revising: "Remove vague advice, expose tradeoffs, and turn each recommendation into an executable step.",
    voice: "Calm, concrete, and solution-focused.",
  },
  {
    id: 17,
    name: "the chronicler",
    summary: "make causality visible through time",
    planning: "Mark the starting condition, turning points, decisions, and the consequence of each transition.",
    drafting: "Advance chronologically while explaining why each moment changes what follows.",
    revising: "Compress uneventful spans, clarify turning points, and prevent chronology from becoming a mere list.",
    voice: "Grounded, sequential, and attentive to change.",
  },
  {
    id: 18,
    name: "the systems thinker",
    summary: "trace feedback loops, incentives, and second-order effects",
    planning: "Map actors, flows, constraints, reinforcing loops, balancing loops, and likely unintended consequences.",
    drafting: "Explain the system from local behavior outward, showing how interactions create the larger pattern.",
    revising: "Add missing feedback, distinguish stocks from events, and test recommendations for side effects.",
    voice: "Connected, strategic, and alert to non-obvious consequences.",
  },
  {
    id: 19,
    name: "the case builder",
    summary: "derive a general lesson from one concrete example",
    planning: "Choose a representative case, isolate the key decision, gather relevant context, and define what can generalize.",
    drafting: "Present the case, analyze the decisive moments, then extract a bounded lesson.",
    revising: "Cut irrelevant biography, challenge the generalization, and connect evidence tightly to the lesson.",
    voice: "Concrete, investigative, and grounded in particulars.",
  },
  {
    id: 20,
    name: "the metaphor maker",
    summary: "use one strong analogy to organize a difficult idea",
    planning: "Choose a source image, map its useful correspondences, and mark exactly where the analogy breaks.",
    drafting: "Introduce the difficult idea through the analogy, then translate each mapped element back to literal terms.",
    revising: "Remove mixed metaphors, state the analogy's limit, and ensure imagery clarifies rather than decorates.",
    voice: "Vivid, accessible, and disciplined.",
  },
  {
    id: 21,
    name: "the conversationalist",
    summary: "reason with the reader in a natural spoken cadence",
    planning: "Anticipate the reader's first question, likely follow-up, moment of doubt, and the simplest honest answer.",
    drafting: "Write as a focused exchange, varying sentence length and answering objections when they naturally arise.",
    revising: "Remove filler, keep the warmth, and make casual phrasing carry precise meaning.",
    voice: "Direct, approachable, and intelligent without stiffness.",
  },
  {
    id: 22,
    name: "the formalist",
    summary: "build a rigorous argument with explicit definitions",
    planning: "Define terms, state premises, order propositions, and note the conditions under which the conclusion holds.",
    drafting: "Proceed through explicit claims and supporting reasons with controlled transitions.",
    revising: "Remove ambiguity, repair logical gaps, and make terminology consistent from beginning to end.",
    voice: "Formal, exact, and restrained.",
  },
  {
    id: 23,
    name: "the punch-up writer",
    summary: "drive attention through sharp claims and energetic rhythm",
    planning: "Find the strongest hook, three high-impact points, one reversal, and the cleanest ending line.",
    drafting: "Lead hard, alternate short and medium beats, and make each paragraph land one memorable point.",
    revising: "Cut soft openings, replace abstractions with active language, and sharpen the final sentence.",
    voice: "Bold, compact, and high-energy without becoming noisy.",
  },
  {
    id: 24,
    name: "the lyricist",
    summary: "shape meaning through image, sound, and controlled repetition",
    planning: "Collect a small image system, emotional movement, recurring phrase, and a plain factual spine.",
    drafting: "Layer concrete images around the factual spine, using rhythm and repetition deliberately.",
    revising: "Remove ornamental lines, vary repeated language, and keep every image tied to the central meaning.",
    voice: "Lyrical, sensory, and controlled rather than purple.",
  },
  {
    id: 25,
    name: "the socratic guide",
    summary: "lead the reader to insight through a sequence of questions",
    planning: "Design questions that expose assumptions, create a contradiction, and let the answer become unavoidable.",
    drafting: "Alternate concise questions with grounded answers, increasing depth with each turn.",
    revising: "Remove rhetorical traps, ensure each question advances the argument, and state the final insight plainly.",
    voice: "Probing, collaborative, and intellectually playful.",
  },
  {
    id: 26,
    name: "the contrarian",
    summary: "begin with the overlooked exception and rebuild the default view",
    planning: "Name the conventional answer, find where it fails, distinguish useful dissent from novelty, and define a better frame.",
    drafting: "Present the common view fairly, reveal its blind spot, then build the alternative from evidence.",
    revising: "Remove performative disagreement, preserve valid parts of the consensus, and make the alternative actionable.",
    voice: "Provocative, fair, and evidence-led.",
  },
  {
    id: 27,
    name: "the evidence ladder",
    summary: "climb from observation to inference in explicit steps",
    planning: "Sort material into direct observations, strong inferences, tentative implications, and unsupported possibilities.",
    drafting: "Start with what is known, then climb one justified inferential step at a time.",
    revising: "Label uncertainty, remove unsupported jumps, and strengthen the link between each rung.",
    voice: "Transparent, cumulative, and trustworthy.",
  },
  {
    id: 28,
    name: "the design critic",
    summary: "judge choices by the experience and behavior they create",
    planning: "Identify the user goal, design intent, actual behavior, friction points, and the highest-leverage change.",
    drafting: "Move from observed experience to underlying design choice, then propose a concrete improvement.",
    revising: "Separate taste from usability, prioritize findings, and tie every critique to an effect.",
    voice: "Observant, candid, and constructive.",
  },
  {
    id: 29,
    name: "the executive",
    summary: "turn complexity into a decision-ready brief",
    planning: "Identify the decision, recommendation, supporting facts, material risks, and immediate next action.",
    drafting: "Lead with the recommendation, then supply only the context needed to assess it.",
    revising: "Move decisions upward, quantify where possible, and eliminate background that does not change action.",
    voice: "Concise, accountable, and oriented toward decisions.",
  },
  {
    id: 30,
    name: "the sculptor",
    summary: "write abundantly, then reveal the final shape through visible cuts",
    planning: "Gather surplus angles, candidate openings, rough claims, and several pieces that may later be discarded.",
    drafting: "Produce a deliberately overcomplete draft in uneven blocks, then discover its strongest center.",
    revising: "Perform the deepest transformation: delete whole passages, merge ideas, reorder paragraphs, and recast the opening.",
    voice: "Layered, exploratory, and increasingly clean as revision progresses.",
  },
] as const;

export function getWritingStyle(id: number): WritingStyle | null {
  return WRITING_STYLES.find((style) => style.id === id) ?? null;
}
